## Numpy array and basics
Learn about Numpy from Chai aur Code

In [5]:
import numpy as np
import time

### Creating array from list

In [3]:
array_1d = np.array([1, 2, 3, 4])
print("Array in 1D: ", array_1d)

array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("Array in 2D: ", array_2d)


Array in 1D:  [1 2 3 4]
Array in 2D:  [[1 2 3 4]
 [5 6 7 8]]


### Python List vs Numpy Array

In [7]:
py_list = [1,2,3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1,2,3])
print("Numpy array multiplication: ", np_array * 2)


start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("Array operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Numpy array multiplication:  [2 4 6]
List operation time:  0.0762321949005127
Array operation time:  0.008107423782348633


### Creating array from scratch

In [ ]:
zeroes = np.zeros((3,3))
print("Zeroes array: \n", zeroes)

ones = np.ones((4, 4))
print("Ones array: \n", ones)

same = np.full((3,3), 9)
print("Full array: \n", same)

random = np.random.random((5, 5))
print("Random array: \n", random)

sequence = np.arange(1, 20, 2)
print("Sequence array: \n", sequence)

Zeroes array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Random array: 
 [[0.59761667 0.14815443 0.36095165 0.17677728 0.68486369]
 [0.47827491 0.06919339 0.0553459  0.20798057 0.70868069]
 [0.24631655 0.12807689 0.47845673 0.44614776 0.14753682]
 [0.23800832 0.73226583 0.63516431 0.65274994 0.05643052]
 [0.08336246 0.53849565 0.44200299 0.57724939 0.8126811 ]]
Sequence array: 
 [ 1  3  5  7  9 11 13 15 17 19]


### Vector, Matrix and Tensor

In [16]:
vector = np.array([1,2,3])

matrix = np.array([[1,2,3],
                   [4,5,6]])

tensor = np.array([[[1,2], [3,4],
                    [5,6], [7,8]]])

### Array Properties

In [17]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Size: ", arr.size)
print("Shape: ", arr.shape)
print("Dimention: ", arr.ndim)
print("DType: ", arr.dtype)

Size:  6
Shape:  (2, 3)
Dimention:  2
DType:  int64


### Array Reshaping

In [24]:
arr = np.arange(12)
print("Orignal Array: \n", arr)

reshape = arr.reshape((3,4))
print("Reshape Array: \n", reshape)

flatten = reshape.flatten()
print("Flattened Array: \n", flatten)

# Ravel returns view instead of copy
ravel = reshape.ravel()
print("Ravel Array: \n", ravel)

transpose = reshape.T
print("Transpose Array: \n", transpose)




Orignal Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
