## Numpy and Array Operations

In [1]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing: ", arr[1:5])
print("Step slicing: ", arr[1:6:2])
print("Negative index: ", arr[-3])

Basic slicing:  [2 3 4 5]
Step slicing:  [2 4 6]
Negative index:  7


In [12]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element: ", arr_2d[1,1])
print("Entire Row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:,1])

Specific Element:  5
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


### Sorting

In [19]:
arr = np.array([5,8,3,1,7,8,0])
print("Sorted 1D array: ", np.sort(arr))

arr_2d = np.array([[2,5,1],
                   [6,3,9],
                   [11,4,3]])
print("Sorted 2D array:\n ", np.sort(arr_2d, axis=1))

# Axis = 1 means each row independent hai and sort in that order like [2,5,1] -> [1,2,5]
# Axis = 0 means each column independent hai and sort in that order like if column [5,3,4] -> [3,4,5]


Sorted 1D array:  [0 1 3 5 7 8 8]
Sorted 2D array:
  [[ 1  2  5]
 [ 3  6  9]
 [ 3  4 11]]


### Filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_numbers = numbers[numbers % 2 == 0]    # inside [ ] is mask -> evaluated expression
print("Even numbers: ", even_numbers)

Even numbers:  [2 4 6 8]


### Filter with Mask


In [22]:
# Mask is nothing but evaluated expression that you can put in array !
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [6 7 8 9]


### Fancy Indexing and np.where()

In [26]:
fancy_index = [2,4,6]
print("Indexes at fancy positions: ", numbers[fancy_index])

where_clause = np.where(numbers > 5)        # This is same as using mask !
print("Numbers greater than 5: ", numbers[where_clause])


# Another very common use case of where clause
condition_array = np.where(numbers > 5, numbers*4, numbers)
print("Conditional array: ", condition_array)

# Think of this like this if ( numbers > 5 ){numbers *4} else {numbers}

Indexes at fancy positions:  [3 5 7]
Numbers greater than 5:  [6 7 8 9]
Conditional array:  [ 1  2  3  4  5 24 28 32 36]


### Adding and Removing Data

In [29]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

addition = arr1 + arr2
print("Addition of both arrays: ", addition)  # Adds two arrays 

combine = np.concatenate((arr1, arr2))
print("Comibining both arrays: ",combine)

Addition of both arrays:  [5 7 9]
Comibining both arrays:  [1 2 3 4 5 6]


### Array Compatibility (Imp for addition and multiplication)

In [31]:
# If you want to check for shape
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([4,5,6,7])


print("Are they compatible : ", a.shape == b.shape)
print("Are they compatible : ", a.shape == c.shape)

Are they compatible :  True
Are they compatible :  False


### Row/Column Add Karna 

In [40]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([6,7])
new_array = np.vstack((a1,a2))   # Yeh thora confusing hai vstack means vertical but adds a row
print(a1)
print(new_array)

a3 = np.array([[8], [9]])
new_array2 = np.hstack((a1,a3))
print(a1)
print(new_array2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [6 7]]
[[1 2]
 [3 4]]
[[1 2 8]
 [3 4 9]]


### Deletion in Array 

In [42]:
test_array = np.array([1,2,3,4,5,5,6])
deleted_array = np.delete(test_array, [4, 6])
print(deleted_array)

[1 2 3 4 5]
